//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIENTU
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int gioHangID { get; set; }
        public int khachHangID { get; set; }
        public int sanphamID { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<decimal> donGia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
